#name: glcortex-devsecops
#run-name: ${{ github.actor }} is learning GitHub Actions
#on: [push]
#jobs:
#  info:
#    runs-on: ubuntu-latest
#    steps:
#      - run: uname -a
#      - run: id
#      - run: env
#  security:
#    runs-on: ubuntu-latest
#    steps:
#      - uses: actions/checkout@master
#      - name: Run Snyk to check for vulnerabilities
#        uses: snyk/actions/node@master
#        env:
#          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}

name: Glcortex workflow using Snyk
on: push
jobs:
  security:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: Run Snyk to check for vulnerabilities
        uses: snyk/actions/node@master
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
